learningdjango/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url

"""include((pattern_list, app_namespace), namespace)"""
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('learningdjangos.urls', 'learningdjangos'), namespace='learningdjangos')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
]

learningdjangos/urls.py
"""定义learningdjangos的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),
    # topics
    url(r'^topics/$', views.topics, name='topics'),
    # specific topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # new_topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # new_entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # edit entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""定义users的URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

Django-3.0.4/django/contrib/gis/db/backends/base/models.py
from django.contrib.gis import gdal


class SpatialRefSysMixin:
    """
    The SpatialRefSysMixin is a class used by the database-dependent
    SpatialRefSys objects to reduce redundant code.
    """
    @property
    def srs(self):
        """
        Return a GDAL SpatialReference object.
        """
        # TODO: Is caching really necessary here?  Is complexity worth it?
        if hasattr(self, '_srs'):
            # Returning a clone of the cached SpatialReference object.
            return self._srs.clone()
        else:
            # Attempting to cache a SpatialReference object.

            # Trying to get from WKT first.
            try:
                self._srs = gdal.SpatialReference(self.wkt)
                return self.srs
            except Exception as e:
                msg = e

            try:
                self._srs = gdal.SpatialReference(self.proj4text)
                return self.srs
            except Exception as e:
                msg = e

            raise Exception('Could not get OSR SpatialReference from WKT: %s\nError:\n%s' % (self.wkt, msg))

    @property
    def ellipsoid(self):
        """
        Return a tuple of the ellipsoid parameters:
        (semimajor axis, semiminor axis, and inverse flattening).
        """
        return self.srs.ellipsoid

    @property
    def name(self):
        "Return the projection name."
        return self.srs.name

    @property
    def spheroid(self):
        "Return the spheroid name for this spatial reference."
        return self.srs['spheroid']

    @property
    def datum(self):
        "Return the datum for this spatial reference."
        return self.srs['datum']

    @property
    def projected(self):
        "Is this Spatial Reference projected?"
        return self.srs.projected

    @property
    def local(self):
        "Is this Spatial Reference local?"
        return self.srs.local

    @property
    def geographic(self):
        "Is this Spatial Reference geographic?"
        return self.srs.geographic

    @property
    def linear_name(self):
        "Return the linear units name."
        return self.srs.linear_name

    @property
    def linear_units(self):
        "Return the linear units."
        return self.srs.linear_units

    @property
    def angular_name(self):
        "Return the name of the angular units."
        return self.srs.angular_name

    @property
    def angular_units(self):
        "Return the angular units."
        return self.srs.angular_units

    @property
    def units(self):
        "Return a tuple of the units and the name."
        if self.projected or self.local:
            return (self.linear_units, self.linear_name)
        elif self.geographic:
            return (self.angular_units, self.angular_name)
        else:
            return (None, None)

    @classmethod
    def get_units(cls, wkt):
        """
        Return a tuple of (unit_value, unit_name) for the given WKT without
        using any of the database fields.
        """
        return gdal.SpatialReference(wkt).units

    @classmethod
    def get_spheroid(cls, wkt, string=True):
        """
        Class method used by GeometryField on initialization to
        retrieve the `SPHEROID[..]` parameters from the given WKT.
        """
        srs = gdal.SpatialReference(wkt)
        sphere_params = srs.ellipsoid
        sphere_name = srs['spheroid']

        if not string:
            return sphere_name, sphere_params
        else:
            # `string` parameter used to place in format acceptable by PostGIS
            if len(sphere_params) == 3:
                radius, flattening = sphere_params[0], sphere_params[2]
            else:
                radius, flattening = sphere_params
            return 'SPHEROID["%s",%s,%s]' % (sphere_name, radius, flattening)

    def __str__(self):
        """
        Return the string representation, a 'pretty' OGC WKT.
        """
        return str(self.srs)

learningdjangos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):

    text = models.CharField(max_length=200)
    date_add = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

learningdjangos/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learningdjangos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """homepage view"""
    return render(request, 'learningdjangos/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_add')
    context = {'topics': topics}
    return render(request, 'learningdjangos/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_add')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learningdjangos/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learningdjangos:topics'))

    context = {'form': form}
    return render(request, 'learningdjangos/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learningdjangos:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learningdjangos/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learningdjangos:topic',
                                                args=[topic.id]))

    context = {'entry': entry, "topic": topic, 'form': form}
    return render(request, 'learningdjangos/edit_entry.html', context)

learningdjangos/templates/learningdjangos/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Learning Django</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>

        <!-- Static navbar -->
    <nav class="narbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learningdjangos:index' %}">
                    Learning Django
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'learningdjangos:topics' %}">
                            Topics
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a>
                                Hello,{{ user.username }}.
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'users:logout' %}">
                                log out
                            </a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.nav-collaspe -->
        </div>
    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
    </body>
</html>

learningdjangos/templates/learningdjangos/edit_entry.html
{% extends 'learningdjangos/base.html' %}

{% block content %}
    <p><a href="{% url 'learningdjangos:topic' topic.id %}">{{ topic }}</a> </p>

    <p>Edit entry:</p>
    <form action="{% url 'learningdjangos:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
{% endblock content %}

learningdjangos/templates/learningdjangos/index.html
{% extends "learningdjangos/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
    </h2>
{% endblock content %}

learningdjangos/templates/learningdjangos/new_entry.html
{% extends 'learningdjangos/base.html' %}

{% block content %}

    <p><a href="{% url 'learningdjangos:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'learningdjangos:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>

{% endblock content %}

learningdjangos/templates/learningdjangos/new_topic.html
{% extends 'learningdjangos/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}


    <form action="{% url 'learningdjangos:new_topic' %}" method="post"
            class="form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {%  buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

{% endblock content %}

learningdjangos/templates/learningdjangos/topic.html
{% extends "learningdjangos/base.html" %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}


    <p>
        <a href="{% url 'learningdjangos:new_entry' topic.id %}">add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="pannel pannel-default">
            <div class="pannel-heading">
                <h3>
                    {{ entry.date_add|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learningdjangos:edit_entry' entry.id %}">
                            edit entry
                        </a>
                    </small>
                </h3>
            </div>
            <div class="pannel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- pannel -->
    {% empty %}
            <li>
                There is no entry for this topic yet.
            </li>
    {% endfor %}

{% endblock content %}

learningdjangos/templates/learningdjangos/topics.html
{% extends "learningdjangos/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learningdjangos:topic' topic.id %}" >{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>No topic has been added yet.</li>
        {% endfor %}
    </ul>

    <h3>
        <a href="{% url 'learningdjangos:new_topic' %}">Add a new topic:</a>
    </h3>

{% endblock content %}